default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: 123

development:
  <<: *default
  database: food_app

test:
  <<: *default
  database: food_app_test

production:
  <<: *default
  database: food_app_production
